import { Nunito_Sans } from "next/font/google";
import { Header, Providers } from "@/components";

import "@/styles/globals.scss";
import s from "./layout.module.scss";

const nunito = Nunito_Sans({
  weight: ["300", "400", "600", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Where in the world?",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en" className={nunito.className} suppressHydrationWarning>
    <head />
    <body>
      <Providers>
        <div className={s.wrapper}>
          <Header />
          <main className={s.main} data-container="fixed">
            {children}
          </main>
        </div>
      </Providers>
    </body>
  </html>
);

export default RootLayout;
